with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/jbeshir/mcp-servers/assets/internal/assetcore:
    interfaces:
      IconProvider:
      IllustrationProvider:
      FontProvider:
      PhotoProvider:
      TextureProvider:
      ModelProvider:
      AudioProvider:
