// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	assetcore "github.com/jbeshir/mcp-servers/assets/internal/assetcore"

	mock "github.com/stretchr/testify/mock"
)

// FontProvider is an autogenerated mock type for the FontProvider type
type FontProvider struct {
	mock.Mock
}

type FontProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FontProvider) EXPECT() *FontProvider_Expecter {
	return &FontProvider_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, id, opts
func (_m *FontProvider) Fetch(ctx context.Context, id string, opts assetcore.FontFetchOpts) (assetcore.Blob, error) {
	ret := _m.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 assetcore.Blob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, assetcore.FontFetchOpts) (assetcore.Blob, error)); ok {
		return rf(ctx, id, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, assetcore.FontFetchOpts) assetcore.Blob); ok {
		r0 = rf(ctx, id, opts)
	} else {
		r0 = ret.Get(0).(assetcore.Blob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, assetcore.FontFetchOpts) error); ok {
		r1 = rf(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FontProvider_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type FontProvider_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts assetcore.FontFetchOpts
func (_e *FontProvider_Expecter) Fetch(ctx interface{}, id interface{}, opts interface{}) *FontProvider_Fetch_Call {
	return &FontProvider_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id, opts)}
}

func (_c *FontProvider_Fetch_Call) Run(run func(ctx context.Context, id string, opts assetcore.FontFetchOpts)) *FontProvider_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(assetcore.FontFetchOpts))
	})
	return _c
}

func (_c *FontProvider_Fetch_Call) Return(_a0 assetcore.Blob, _a1 error) *FontProvider_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FontProvider_Fetch_Call) RunAndReturn(run func(context.Context, string, assetcore.FontFetchOpts) (assetcore.Blob, error)) *FontProvider_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Kind provides a mock function with no fields
func (_m *FontProvider) Kind() assetcore.Kind {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 assetcore.Kind
	if rf, ok := ret.Get(0).(func() assetcore.Kind); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(assetcore.Kind)
	}

	return r0
}

// FontProvider_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type FontProvider_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *FontProvider_Expecter) Kind() *FontProvider_Kind_Call {
	return &FontProvider_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *FontProvider_Kind_Call) Run(run func()) *FontProvider_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FontProvider_Kind_Call) Return(_a0 assetcore.Kind) *FontProvider_Kind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FontProvider_Kind_Call) RunAndReturn(run func() assetcore.Kind) *FontProvider_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *FontProvider) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FontProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type FontProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *FontProvider_Expecter) Name() *FontProvider_Name_Call {
	return &FontProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *FontProvider_Name_Call) Run(run func()) *FontProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FontProvider_Name_Call) Return(_a0 string) *FontProvider_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FontProvider_Name_Call) RunAndReturn(run func() string) *FontProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, opts
func (_m *FontProvider) Search(ctx context.Context, opts assetcore.SearchOpts) (assetcore.SearchResult, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 assetcore.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, assetcore.SearchOpts) (assetcore.SearchResult, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, assetcore.SearchOpts) assetcore.SearchResult); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(assetcore.SearchResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, assetcore.SearchOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FontProvider_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type FontProvider_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - opts assetcore.SearchOpts
func (_e *FontProvider_Expecter) Search(ctx interface{}, opts interface{}) *FontProvider_Search_Call {
	return &FontProvider_Search_Call{Call: _e.mock.On("Search", ctx, opts)}
}

func (_c *FontProvider_Search_Call) Run(run func(ctx context.Context, opts assetcore.SearchOpts)) *FontProvider_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(assetcore.SearchOpts))
	})
	return _c
}

func (_c *FontProvider_Search_Call) Return(_a0 assetcore.SearchResult, _a1 error) *FontProvider_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FontProvider_Search_Call) RunAndReturn(run func(context.Context, assetcore.SearchOpts) (assetcore.SearchResult, error)) *FontProvider_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewFontProvider creates a new instance of FontProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFontProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FontProvider {
	mock := &FontProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
